global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'auth-service-monitor'

scrape_configs:
  - job_name: 'auth-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          application: 'auth-user-service'
          environment: 'docker'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          database: 'authdb'
